# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="oxide"
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set value from 0 to 7
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=2"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="dd.mm.yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$HOME/dotfiles/zsh/custom

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
asdf
aws
git
git-flow
forgit
copyfile
copypath
docker
docker-compose
pass
zsh-autosuggestions
zsh-vi-mode
fzf-it
fzf-tab
)

ZVM_INIT_MODE=sourcing


source $ZSH/oh-my-zsh.sh

# User configuration
setopt share_history
setopt HIST_IGNORE_SPACE


ZVM_VI_INSERT_ESCAPE_BINDKEY=jk

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Normal Aliases

alias psql="docker run --rm --net host -it postgres:14.5-alpine sh -c \"psql localhost:5432 --user postgres"
alias ngs="nv -c \"Git | wincmd o\""
alias gsfe="git submodule foreach"
alias draw="/home/dangelo/.appimg/draw.io-x86_64-13.7.9.AppImage &>/dev/null & disown"
alias hugo="docker run --rm -it -v $PWD:/src  klakegg/hugo:ext-alpine"
alias hugo-server="docker run --rm -it  -v $PWD:/src  -p 1313:1313  klakegg/hugo:ext-alpine server"
alias kpm="~/development/docker/kpm/runServer.sh"
alias nv="nvim"
alias zconf="nvim ~/.zshrc"
alias zvconf="nvim $ZSH_CUSTOM/nvim.zsh"
alias zfconf="nvim $ZSH_CUSTOM/fzf.zsh"
alias zficonf="nvim $ZSH_CUSTOM/dotfiles/zsh/custom/plugins/fzf-it/fzf-it.plugin.zsh"
alias gconf="nvim ~/.gitconfig"
alias tconf="nvim ~/.tmux.conf"
alias iconf="nvim ~/dotfiles/i3/config"
alias nconf="nvim ~/dotfiles/LazyVim/"
alias ldconf="nvim ~/.config/lazydocker/config.yml"
alias lgconf="nvim ~/.config/lazygit/config.yml"
alias aconf="nvim ~/.config/alacritty/alacritty.toml"
alias szsh="source ~/.zshrc"
alias k="kubectl"
alias ke="kubectl --namespace=edge"
alias kba="kubectl --namespace=backend-api"
alias kin="kubectl --namespace=ingress-nginx"
# alias tmuxs="tmux attach -t main || tmux new -s main"
# alias tmux="tmux -2"
alias octave="flatpak run org.octave.Octave"
alias py="python3"
alias m="multipass"
alias dc="docker compose"
alias ldd="lazydocker -f dev.docker-compose.yml"
alias ld="lazydocker"
alias lg="lazygit"
alias gg="lazygit"
alias gdm="git branch --merged | egrep -v '(^\*|master|main|dev)' | xargs git branch -d"
alias gswr="git reflog | egrep -io 'moving from ([^[:space:]]+)' | awk '{ print \$3 }' | awk ' !x[\$0]++' | egrep -v '^[a-f0-9]{40}$' | head -n100 | fzf --bind 'enter:execute(git switch {})+abort' --height 50%"
alias gmt="git mergetool"



# Prefix aliases
alias -s pdf='zathura'
alias -s py='nvim'
alias -s js='nvim'
alias -s txt='nvim'
alias -s mkv='vlc'
alias -s mkv='vlc'
alias -s png='eog'
alias -s jpg='eog'

# Expandable aliases
alias -g D='& disown'

function expand-alias() {
	zle _expand_alias
	zle self-insert
}
zle -N expand-alias
bindkey -M main ' ' expand-alias

function jwt_decode(){
    jq -R 'split(".") | .[1] | @base64d | fromjson' <<< "$1"
}

function curlit() {

  usage() {
    echo "Usage: $(basename "$0") [-j <jq_query>] [-d <string>] [-h]" >&2
    echo "Options:" >&2
    echo "  -j <jq_query>    JQ query to filter input" >&2
    echo "  -q <jq_query>    JQ query to filter input" >&2
    echo "  -d <variable>    Variable to save query result" >&2
    echo "  -h               Print usage instructions" >&2
  }

  local jq_query=""
  local variable=""

  while getopts ":j:d:h:q" opt; do
    case ${opt} in
      j )
        jq_query="$OPTARG"
        ;;
      q )
        query="$OPTARG"
        ;;
      d )
        variable="$OPTARG"
        ;;
      h )
        usage
        return 0
        ;;
      \? )
        echo "Invalid option: -$OPTARG" >&2
        usage
        return 1
        ;;
      : )
        echo "Option -$OPTARG requires an argument." >&2
        usage
        return 1
        ;;
    esac
  done

  if [ -n "$variable" ] && [ -z "$jq_query" ]; then
    echo "Error: You must pass the -j flag when using the -d flag" >&2
    usage
    return 1
  fi

  local response="$(cat)"

  echo -E "$response" | awk '/^HTTP/{if($2~/2../)print "\033[32m"$0"\033[0m"; else if($2~/3../)print "\033[33m"$0"\033[0m"; else if($2~/4../)print "\033[31m"$0"\033[0m"; else if($2~/5../)print "\033[35m"$0"\033[0m"; else print}'
  local body=$(echo -E "$response" | sed '1,/^\r$/d' | jq -r '. as $raw | try fromjson catch $raw ')

  echo -E "$body" | jq

  # status_code=$(echo "$response" | awk '/^HTTP/{print $2}')
  # if [ "$status_code" != "200" ]; then
  #   return 1
  # fi

  if [ -n "$jq_query" ] && [ -n "$variable" ]; then
    echo -E "$body" | jq -r "$jq_query" > "$variable"
    jq_query=""
  fi

  if [ -n "$jq_query" ]; then
    echo -E "$body" | jq -r "$jq_query"
  fi

  if [ -n "$query" ]; then
    echo -E "$body" | jq -r "$query"
  fi

}

mkcd ()
{
    mkdir -p -- "$1" && cd -P -- "$1"
}

mkfile() { mkdir -p "$(dirname "$1")" && touch "$1" ;  }

runhis() {
    history | fzf -m -q "$1" | awk '{ print substr($0, index($0,$4))  }' | bash
}

c() {
  local cols sep google_history open
  cols=$(( COLUMNS / 3 ))
  sep='{::}'

  if [ "$(uname)" = "Darwin" ]; then
    google_history="$HOME/Library/Application Support/Google/Chrome/Default/History"
    open=open
  else
    google_history="$HOME/.config/google-chrome/Default/History"
    open=xdg-open
  fi
  cp -f "$google_history" /tmp/h
  sqlite3 -separator $sep /tmp/h \
    "select substr(title, 1, $cols), url
     from urls order by last_visit_time desc" |
  awk -F $sep '{printf "%-'$cols's  \x1b[36m%s\x1b[m\n", $1, $2}' |
  fzf --ansi --multi | sed 's#.*\(https*://\)#\1#' | xargs $open > /dev/null 2> /dev/null
}

# fkill - kill processes - list only the ones you can kill. Modified the earlier script.
fkill() {
    local pid
    if [ "$UID" != "0" ]; then
        pid=$(ps -f -u $UID | sed 1d | fzf -m | awk '{print $2}')
    else
        pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')
    fi

    if [ "x$pid" != "x" ]
    then
        echo $pid | xargs kill -${1:-9}
    fi
}

# Codi
# Usage: codi [filetype] [filename]
codi() {
  local syntax="${1:-python}"
  shift
  nvim -c \
    "let g:startify_disable_at_vimenter = 1 |\
    set bt=nofile ls=0 noru nonu nornu |\
    hi ColorColumn ctermbg=NONE |\
    hi VertSplit ctermbg=NONE |\
    hi NonText ctermfg=0 |\
    Codi $syntax" "$@"
}

FORGIT_COPY_CMD='xclip -selection clipboard'

# export JAVA_HOME="/usr/lib/jvm/jdk-15.0.2"
# export JAVA_HOME="/usr/lib/jvm/jdk1.8.0_281"
export JAVA_HOME="/usr/lib/jvm/jdk1.8.0_291/"
export PATH="$JAVA_HOME/bin:$PATH"
# export PATH="$JAVA_HOME/bin:/snap/bin:$PATH"
# export CLASS_PATH="/home/dangelo/studying/java_101/authorizeTransactions:/home/dangelo/studying/java_101/authorizeTransactions/lib/"
# export PYENV_ROOT="$HOME/.pyenv"
# export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$HOME/.symfony/bin:$PATH"
export GOPATH="$HOME/go"
export GOBIN="$HOME/go/bin"
export GOROOT="/usr/local/go"
export PATH="$GOPATH:$GOBIN:$GOROOT/bin:$PATH"
export PATH="/usr/lib/protobuf-3.15.8:$PATH" # PROTOBUF
export PATH="/usr/lib/wabt-1.0.23/bin:$PATH" # WABT
export PATH="/usr/bin/aws:$PATH" # AWS
export PATH="$HOME/.local/bin:$PATH" # AWS
export EDITOR="nvim"
export NNN_FIFO="/tmp/nnn.fifo"
export NNN_PLUG='f:finder;o:fzopen;p:mocplay;d:diffs;t:nmount;v:imgview;x:!chmod +x $nnn;X:!chmod -x $nnn;g:!git log;s:preview-tui'
export COMPOSE_DOCKER_CLI_BUILD=1
# ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=1,bg=cyan,bold,underline"
autoload -Uz compinit && compinit -i
# autoload bashcompinit && bashcompinit
# complete -C '/usr/bin/aws_completer' aws

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# enable kubect autocompletion
# [[ /usr/bin/kubectl ]] && source <(kubectl completion zsh)

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
# [ -s "$HOME/.zsh/completion" ] && \. "$HOME/.zsh/completion"  # This loads nvm bash_completion

export WASMTIME_HOME="$HOME/.wasmtime"

export PATH="$WASMTIME_HOME/bin:$PATH"
. "$HOME/.cargo/env"

# Put the line below in ~/.zshrc:
eval "$(jump shell zsh)"

mkdir -p ${ZDOTDIR:-~}/.zsh_functions
fpath+=${ZDOTDIR:-~}/.zsh_functions


