# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="oxide"
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set value from 0 to 7
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=2"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="dd.mm.yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$HOME/dotfiles/zsh/custom

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
aws
git
git-flow
forgit
copyfile
copypath
docker
docker-compose
pass
zsh-autosuggestions
zsh-vi-mode
fzf-it
fzf-tab
)

ZVM_INIT_MODE=sourcing
ZVM_VI_INSERT_ESCAPE_BINDKEY=jk

source $ZSH/oh-my-zsh.sh

# User configuration
setopt share_history
setopt HIST_IGNORE_SPACE

#Aliases

alias psql="docker run --rm --net host -it postgres:14.5-alpine sh -c \"psql localhost:5432 --user postgres"
alias ngs="nv -c \"Git | wincmd o\""
alias gsfe="git submodule foreach"
# alias draw="/home/dangelo/.appimg/draw.io-x86_64-13.7.9.AppImage &>/dev/null & disown"
alias hugo="docker run --rm -it -v $PWD:/src  klakegg/hugo:ext-alpine"
alias hugo-server="docker run --rm -it  -v $PWD:/src  -p 1313:1313  klakegg/hugo:ext-alpine server"
alias kpm="~/development/docker/kpm/runServer.sh"
alias nv="nvim"
alias zconf="nvim ~/.zshrc"
alias zvconf="nvim $ZSH_CUSTOM/nvim.zsh"
alias zfconf="nvim $ZSH_CUSTOM/fzf.zsh"
alias zficonf="nvim $ZSH_CUSTOM/dotfiles/zsh/custom/plugins/fzf-it/fzf-it.plugin.zsh"
alias gconf="nvim ~/.gitconfig"
alias tconf="nvim ~/.tmux.conf"
alias iconf="nvim ~/dotfiles/i3/config"
alias nconf="nvim ~/dotfiles/LazyVim/"
alias ldconf="nvim ~/.config/lazydocker/config.yml"
alias lgconf="nvim ~/.config/lazygit/config.yml"
alias aconf="nvim ~/.config/alacritty/alacritty.toml"
alias szsh="source ~/.zshrc"
alias ezsh="exec zsh"
alias k="kubectl"
alias ke="kubectl --namespace=edge"
alias kba="kubectl --namespace=backend-api"
alias kin="kubectl --namespace=ingress-nginx"
# alias tmuxs="tmux attach -t main || tmux new -s main"
# alias tmux="tmux -2"
alias octave="flatpak run org.octave.Octave"
alias py="python3"
alias m="multipass"
alias dc="docker compose"
alias ldd="lazydocker -f dev.docker-compose.yml"
alias ld="lazydocker"
alias lg="lazygit"
alias gg="lazygit"
alias gdm="git branch --merged | egrep -v '(^\*|master|main|dev)' | xargs git branch -d"
alias gswr="git reflog | egrep -io 'moving from ([^[:space:]]+)' | awk '{ print \$3 }' | awk ' !x[\$0]++' | egrep -v '^[a-f0-9]{40}$' | head -n100 | fzf --bind 'enter:execute(git switch {})+abort' --height 50%"
alias gmt="git mergetool"
alias fl="fluvio"

# Prefix aliases
alias -s pdf='zathura'
alias -s py='nvim'
alias -s js='nvim'
alias -s txt='nvim'
alias -s mkv='vlc'
alias -s mkv='vlc'
alias -s png='eog'
alias -s jpg='eog'

# Expandable aliases
alias -g D='& disown'

function expand-alias() {
	zle _expand_alias
	zle self-insert
}
zle -N expand-alias
bindkey -M main ' ' expand-alias


export FORGIT_COPY_CMD='xclip -selection clipboard'
export PATH="/usr/lib/protobuf-3.15.8:$PATH" # PROTOBUF
export PATH="/usr/lib/wabt-1.0.23/bin:$PATH" # WABT
export PATH="$HOME/.local/bin:$PATH" # AWS
export EDITOR="nvim"
export NNN_FIFO="/tmp/nnn.fifo"
export NNN_PLUG='f:finder;o:fzopen;p:mocplay;d:diffs;t:nmount;v:imgview;x:!chmod +x $nnn;X:!chmod -x $nnn;g:!git log;s:preview-tui'
export COMPOSE_DOCKER_CLI_BUILD=1
export PATH="${HOME}/.fvm/bin:${HOME}/.fluvio/bin:${PATH}"

export PATH="/opt/nvim-linux-x86_64/bin/:${PATH}"

export GOPATH="${HOME}/go"
export GOBIN="${GOPATH}/bin"
export PATH="${GOBIN}:/usr/local/go/bin/:${PATH}"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export WASMTIME_HOME="$HOME/.wasmtime"
export PATH="$WASMTIME_HOME/bin:$PATH"
[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

command -v fluvio >/dev/null && source <(fluvio completions zsh)
command -v devpod >/dev/null && source <(devpod completion zsh)
command -v jump >/dev/null && eval "$(jump shell zsh)"
command -v devbox >/dev/null && eval "$(devbox global shellenv --init-hook)"

autoload -Uz compinit && compinit -i
