-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
--
-- Run LSP organize imports and format on save
-- vim.api.nvim_create_autocmd("BufWritePre", {
--   pattern = "*.go",
--   callback = function()
--     -- Organize imports
--     vim.lsp.buf.code_action({
--       context = {
--         only = { "source.organizeImports" },
--         diagnostics = {},
--       },
--       apply = true,
--     })
--
--     -- Format buffer
--     vim.lsp.buf.format({ async = false })
--   end,
-- })
